# Generated by Django 4.1.3 on 2022-11-25 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('student_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=400)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('about', models.CharField(max_length=400)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=9)),
                ('amount_type', models.CharField(choices=[('1', 'UZS'), ('2', 'USA'), ('3', 'EURO')], max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markaz.student')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('student_size', models.IntegerField(default=0)),
                ('start_time', models.CharField(max_length=150)),
                ('days', models.CharField(choices=[('1', 'Dushanba'), ('2', 'Seshanba'), ('3', 'Chorshanba'), ('4', 'Payshanba'), ('5', 'Juma'), ('6', 'Shanba'), ('7', 'Yakshanba')], max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Faol'), ('Waiting', 'Kutilyapti'), ('Finished', 'Tugalangan')], max_length=150)),
                ('text', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markaz.classroom')),
                ('students', models.ManyToManyField(blank=True, to='markaz.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markaz.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.CharField(choices=[('ha', '+'), ("yo'q", '-')], max_length=1500)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markaz.group')),
                ('student_id', models.ManyToManyField(to='markaz.student')),
            ],
        ),
    ]
