# Generated by Django 4.1.3 on 2022-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(),
        ),
    ]
